name: Sibling Branch Cache Test

on:
  push:
    branches:
      - 'feature-*'
  workflow_dispatch:

jobs:
  create-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script to generate cache
        run: python src/main.py
        
      - name: Cache timestamp
        uses: actions/cache@v3
        with:
          path: cache
          key: timestamp-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            timestamp-${{ runner.os }}-
            
  verify-isolation:
    needs: create-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Try to restore cache from current branch
        uses: actions/cache@v3
        with:
          path: cache
          key: timestamp-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            timestamp-${{ runner.os }}-
            
      - name: Display cache status
        run: |
          if [ -f cache/timestamp.txt ]; then
            echo "Cache found:"
            cat cache/timestamp.txt
          else
            echo "No cache found"
          fi 
