name: Pull Request Cache Isolation Test

on:
  pull_request:
    branches:
      - 'main-to-featureA'
  workflow_dispatch:

jobs:
  create-pr-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script to generate PR-specific cache
        run: python src/main.py
        
      - name: Cache PR-specific timestamp
        uses: actions/cache@v3
        with:
          path: cache-pr
          key: timestamp-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            timestamp-${{ runner.os }}-
            
  verify-pr-cache-isolation:
    needs: create-pr-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Try to restore PR-specific cache
        uses: actions/cache@v3
        with:
          path: cache-pr
          key: timestamp-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            timestamp-${{ runner.os }}-
            
      - name: Display PR cache status
        run: |
          if [ -f cache-pr/timestamp.txt ]; then
            echo "PR-specific cache found:"
            cat cache-pr/timestamp.txt
            echo "PR reference: ${{ github.ref }}"
          else
            echo "No PR-specific cache found"
          fi
          
      - name: Try to restore cache from base branch
        uses: actions/cache@v3
        with:
          path: cache-base
          key: timestamp-${{ runner.os }}-${{ github.base_ref }}
          restore-keys: |
            timestamp-${{ runner.os }}-
            
      - name: Display base branch cache status
        run: |
          if [ -f cache-base/timestamp.txt ]; then
            echo "Base branch cache found:"
            cat cache-base/timestamp.txt
          else
            echo "No base branch cache found (expected - PR cache should be isolated)"
          fi 
